In [1]:
#QUESTION 1
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print("Array Indexing:")
print(arr[0, 1])
print(arr[2, 2])

print("\nFancy Indexing:")
rows = np.array([0, 2])
cols = np.array([1, 2])
print(arr[rows, cols])

Array Indexing:
2
9

Fancy Indexing:
[2 9]


In [2]:
#QUESTION 2
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print("Original array:")
print(arr)

print("\nSliced array (row 0 to 1, column 1 to 3):")
print(arr[0:2, 1:4])

print("\nSliced array (all rows, column 2):")
print(arr[:, 2])


Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Sliced array (row 0 to 1, column 1 to 3):
[[2 3 4]
 [6 7 8]]

Sliced array (all rows, column 2):
[ 3  7 11]


In [3]:
#QUESTION 3
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)

[[[[[1 2 3 4]]]]]


In [4]:
#QUESTION 4
import numpy as np

arr = np.array([1, 2, 3, 4])
reshaped_arr = arr.reshape(2, 2)

print(reshaped_arr)


[[1 2]
 [3 4]]


In [21]:
#QUESTION 5
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])

vstack_result = np.vstack((arr1, arr2))


hstack_result = np.hstack((arr1, arr2))


dstack_result = np.dstack((arr1, arr2, arr3))


basic_stack_result = np.stack((arr1, arr2))

print("Vertically stacked array:")
print(vstack_result)

print("\nHorizontally stacked array:")
print(hstack_result)

print("\nDepth-wise stacked array:")
print(dstack_result)

print("\nBasic stacked array:")
print(basic_stack_result)


Vertically stacked array:
[[1 2 3]
 [4 5 6]]

Horizontally stacked array:
[1 2 3 4 5 6]

Depth-wise stacked array:
[[[1 4 7]
  [2 5 8]
  [3 6 9]]]

Basic stacked array:
[[1 2 3]
 [4 5 6]]


In [7]:
#QUESION 6
import numpy as np

sorted_array = np.array([10, 20, 30, 40, 50])

value_to_insert = 25

insert_index = np.searchsorted(sorted_array, value_to_insert)

print(f"The index to insert {value_to_insert} is: {insert_index}")


The index to insert 25 is: 2


In [10]:
#QUESTION 7
import numpy as np

user_data_dtype = [
    ('user_id', 'int32'),
    ('name', 'U50'),
    ('age', 'int32'),
    ('weight_kg', 'float64'),
    ('height_cm', 'float64')
]

nutritional_log_dtype = [
    ('log_id', 'int32'),
    ('user_id', 'int32'),
    ('date', 'datetime64[D]'),
    ('calories', 'int32'),
    ('protein_g', 'float64'),
    ('carbs_g', 'float64'),
    ('fat_g', 'float64')
]

user_data_array = np.array([(1, 'Rajesh Kumar', 28, 70.0, 175.0)], dtype=user_data_dtype)
nutritional_log_array = np.array([(1, 1, '2023-09-15', 2000, 80.0, 250.0, 70.0)], dtype=nutritional_log_dtype)

print("User Data:")
print(user_data_array)

print("\nNutritional Log:")
print(nutritional_log_array)


User Data:
[(1, 'Rajesh Kumar', 28, 70., 175.)]

Nutritional Log:
[(1, 1, '2023-09-15', 2000, 80., 250., 70.)]


In [22]:
#QUESTION 8
import pandas as pd
import random


names = []
ages = []
subjects = []


indian_names = ["Amit", "Sneha", "Rajesh", "Priya", "Neha", "Manish", "Anjali", "Vikram", "Meera", "Sanjay", "Pooja", "Rahul", "Divya", "Aarti", "Suresh"]

for _ in range(15):
    name = random.choice(indian_names)
    age = random.randint(16, 20)
    subject = random.choice(["Math", "Science", "History", "English", "Geography"])
    
    names.append(name)
    ages.append(age)
    subjects.append(subject)


data = {
    "Name": names,
    "Age": ages,
    "Subject": subjects
}


df = pd.DataFrame(data)


print(df)


      Name  Age    Subject
0    Priya   20       Math
1   Anjali   16    English
2    Aarti   18    History
3   Manish   16  Geography
4   Vikram   16    History
5    Priya   18  Geography
6    Divya   18  Geography
7    Priya   19    History
8   Sanjay   19    Science
9    Rahul   20    Science
10  Rajesh   16    English
11    Amit   17  Geography
12  Manish   16    History
13    Amit   19    History
14   Sneha   17  Geography


In [17]:
#QUESTION 9
import pandas as pd
import numpy as np

data = {
    'UserID': [1, 2, 3, 4, 5],
    'UserName': ['Anurag', 'Rahul', 'Ajay', 'Vijay', 'Ashok'],
    'Nutritional_Data': [1500, np.nan, 2000, 1800, 2200],
    'Exercise_Data': [45, 30, np.nan, 60, 90],
    'BMI': [24.5, np.nan, 28.1, 22.3, 25.6],
    'Health_Score': [90, 88, np.nan, 95, np.nan]
}

df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

print("\nChecking for missing data:")
print(df.isnull())

print("\nChecking for non-missing data:")
print(df.notnull())

df_dropna = df.dropna()
print("\nDataFrame after dropping rows with missing data:")
print(df_dropna)

df_fillna = df.fillna(0)
print("\nDataFrame after filling missing values with 0:")
print(df_fillna)

df_replace = df.replace(np.nan, -1)
print("\nDataFrame after replacing missing values with -1:")
print(df_replace)

df_interpolate = df.interpolate()
print("\nDataFrame after linear interpolation of missing values:")
print(df_interpolate)


Original DataFrame:
   UserID UserName  Nutritional_Data  Exercise_Data   BMI  Health_Score
0       1   Anurag            1500.0           45.0  24.5          90.0
1       2    Rahul               NaN           30.0   NaN          88.0
2       3     Ajay            2000.0            NaN  28.1           NaN
3       4    Vijay            1800.0           60.0  22.3          95.0
4       5    Ashok            2200.0           90.0  25.6           NaN

Checking for missing data:
   UserID  UserName  Nutritional_Data  Exercise_Data    BMI  Health_Score
0   False     False             False          False  False         False
1   False     False              True          False   True         False
2   False     False             False           True  False          True
3   False     False             False          False  False         False
4   False     False             False          False  False          True

Checking for non-missing data:
   UserID  UserName  Nutritional_Data  Exerc

In [24]:
#QUESTION 10
import pandas as pd
import numpy as np

data = {
    'Nutritional_Data': [1500, np.nan, 2000, 1800, 2200],
    'Exercise_Data': [45, 30, np.nan, 60, 90],
    'BMI': [24.5, np.nan, 28.1, 22.3, 25.6],
    'Health_Score': [90, 88, np.nan, 95, np.nan]
}

index = pd.MultiIndex.from_tuples([('User1', 'Week1'), ('User1', 'Week2'), ('User2', 'Week1'), ('User2', 'Week2'), ('User3', 'Week1')],
                                   names=['UserID', 'Week'])

df = pd.DataFrame(data, index=index)

print("Hierarchical Indexed DataFrame:")
print(df)

Hierarchical Indexed DataFrame:
              Nutritional_Data  Exercise_Data   BMI  Health_Score
UserID Week                                                      
User1  Week1            1500.0           45.0  24.5          90.0
       Week2               NaN           30.0   NaN          88.0
User2  Week1            2000.0            NaN  28.1           NaN
       Week2            1800.0           60.0  22.3          95.0
User3  Week1            2200.0           90.0  25.6           NaN
