QUESTION 1

In [29]:
import numpy as np

matrix1 = np.random.randint(1, 10, (3, 3))
matrix2 = np.random.randint(1, 10, (3, 3))

product_result = np.prod(matrix1)  
multiply_result = np.multiply(matrix1, matrix2)  
dot_product_result = np.dot(matrix1, matrix2)

print("Matrix 1:")
print(matrix1)
print("Matrix 2:")
print(matrix2)

print("Product of all elements (prod):")
print(product_result)  

print("Multiplication of matrix (multiply):")
print(multiply_result)

print("Dot product of matrix (dot):")
print(dot_product_result)

Matrix 1:
[[9 6 1]
 [5 9 6]
 [8 5 7]]
Matrix 2:
[[7 3 9]
 [3 5 2]
 [2 3 2]]
Product of all elements (prod):
4082400
Multiplication of matrix (multiply):
[[63 18  9]
 [15 45 12]
 [16 15 14]]
Dot product of matrix (dot):
[[83 60 95]
 [74 78 75]
 [85 70 96]]


QUESTION 2

In [30]:
import numpy as np

set1 = np.array([1, 2, 3, 4, 5])
set2 = np.array([3, 4, 5, 6, 7])

union_result = np.union1d(set1, set2)
print("Union:", union_result)

intersection_result = np.intersect1d(set1, set2)
print("Intersection:", intersection_result)

difference_result = np.setdiff1d(set1, set2)
print("Set Difference (set1 - set2):", difference_result)

xor_result = np.setxor1d(set1, set2)
print("XOR (Symmetric Difference):", xor_result)

Union: [1 2 3 4 5 6 7]
Intersection: [3 4 5]
Set Difference (set1 - set2): [1 2]
XOR (Symmetric Difference): [1 2 6 7]


QUESTION 3

In [31]:
import numpy as np

random_array = np.random.randint(1, 11, size=10)
print("Original 1D Array: ", random_array)

cumulative_sum = np.cumsum(random_array)
print("Cumulative Sum:", cumulative_sum)

cumulative_product = np.cumprod(random_array)
print("Cumulative Product:", cumulative_product)

discrete_difference = np.diff(random_array, n=3)
print("Discrete Difference (n=3):", discrete_difference)

unique_elements = np.unique(random_array)
print("Unique Elements:", unique_elements)

Original 1D Array:  [ 8  9 10  3  2  1  3  7 10  6]
Cumulative Sum: [ 8 17 27 30 32 33 36 43 53 59]
Cumulative Product: [      8      72     720    2160    4320    4320   12960   90720  907200
 5443200]
Discrete Difference (n=3): [-8 14 -6  3 -1 -3 -6]
Unique Elements: [ 1  2  3  6  7  8  9 10]


QUESTION 4

In [32]:
import numpy as np

array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([10, 20, 30, 40, 50])

result_zip = [x + y for x, y in zip(array1, array2)]
print("Addition using zip():", result_zip)

result_add = np.add(array1, array2)
print("Addition using np.add():", result_add)

def custom_add(x, y):
    return x + y
ufunc = np.frompyfunc(custom_add, 2, 1)
result_custom = ufunc(array1, array2)
print("Addition using user-defined function (frompyfunc()):", result_custom)

Addition using zip(): [11, 22, 33, 44, 55]
Addition using np.add(): [11 22 33 44 55]
Addition using user-defined function (frompyfunc()): [11 22 33 44 55]


QUESTION 5

In [33]:
import numpy as np
from numpy import gcd, lcm
from functools import reduce

elements = np.array([12, 18, 24, 36])

lcm_result = reduce(lcm, elements)
print("LCM of elements:", lcm_result)

gcd_result = reduce(gcd, elements)
print("GCD of elements:", gcd_result)

LCM of elements: 72
GCD of elements: 6
